### ISSUE TITLE
Limited Surface Generation

### ISSUE THREAD

**Issue by fg094** [Kenan2000/CDDA-Structured-Kenan-Modpack#244] opened 2021-11-17 09:31 UTC
I'm not sure if I've set something up wrong, but towns and cities seem to be 50-70% made up of gas stations, mechanic shops, and garages, often back to back. I'm not getting any magiclysm wizard towers, Lab Towers, Fire stations, subways or much of anything besides automotive related buildings, standard houses, and the small office buildings full of servers.

Labs also are generating with no surface connection.  The only exception to this is the starting lab if I choose a lab start, bio weapon labs, and the Doom labs from PK's rebalance.

**Comment by Kenan2000** [comment] 2021-11-17 12:55
@fg094 Hmm, well, take a look at files with "city": definitions in link that I've sent you here https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/search?q=region_overlay, actually, what this means is that files which have "city": definitions edit regional_overlay either adding new structures to spawn in these cities which have their own spawn rates which go into total pool of structures that spawn in cities or they edit existing vanilla structures' spawn rates, as you see, there are very few of such definitions in files, so it's not a problem of any of these mods, it seems to be caused by vanilla city structures' pool changes maybe as well

**Comment by fg094** [comment] 2021-11-17 19:21
I've tried going through and starting a new world with each of those mods disabled and it's still broken no matter which combination I have disabled.
For now I guess I'll just have to use debug map reveal and teleport to access labs since they don't generate with any surface connections.

**Comment by Kenan2000** [comment] 2024-06-21 02:35
Closing this because it's not related to mods but hardcode so there is nothing to fix about this literally

**Closed by Kenan2000** 2024-06-21 02:35 UTC
